import argparse
import sys
from pathlib import Path


BLUEPRINT_ROOT = Path(__file__).resolve().parent
SRC_ROOT = BLUEPRINT_ROOT / "src"
BIN_ROOT = BLUEPRINT_ROOT / "bin"

for path in (SRC_ROOT, BIN_ROOT):
    path_str = str(path)
    if path_str not in sys.path:
        sys.path.insert(0, path_str)

from run_patchcore import main as patchcore_main
from train_coordinate_adapter import (
    ADAPTER_FILENAME,
    train_coordinate_adapter,
)


BACKBONE = "wideresnet50"
LAYERS = ("layer2", "layer3")

RESIZE = 256
IMAGE_SIZE = 224
BATCH_SIZE = 2
NUM_WORKERS = 0

PRETRAIN_EMBED_DIM = 1024
TARGET_EMBED_DIM = 1024
PATCH_SIZE = 3
NUM_NEAREST_NEIGHBOURS = 1

SAMPLER_NAME = "approx_greedy_coreset"
CORESET_PERCENTAGE = 0.1

DEFAULT_SEED = 42
YOLO_CONF_MULTIPLIER = 0.68
LOG_PROJECT = "PatchCore_Blueprint"


def dataset_root(args):
    if args.dataset == "mvtec":
        return Path(args.mvtec_ad_path)
    if args.dataset == "visa":
        return Path(args.visa_path)
    if args.dataset == "loco":
        return Path(args.loco_path)
    raise ValueError(f"Unsupported dataset: {args.dataset}")


def discover_classes(root):
    if not root.is_dir():
        raise FileNotFoundError(f"Dataset root not found: {root}")

    classes = sorted(
        item.name
        for item in root.iterdir()
        if item.is_dir()
        and (item / "train").is_dir()
        and (item / "test").is_dir()
    )

    if not classes:
        raise RuntimeError(
            f"No PatchCore-compatible category folders found under: {root}"
        )

    return classes


def category_workspace(runs_root, class_name):
    return Path(runs_root) / class_name


def validate_blueprint_prerequisites(workspace):
    workspace = Path(workspace)

    calibration = workspace / "final_anisotropic_calibration.json"
    mapping = workspace / "global_classes_mapping.json"

    direct_yolo = workspace / "best.pt"
    legacy_yolo = workspace / "yolo_output" / "weights" / "best.pt"

    missing = []
    if not calibration.is_file():
        missing.append(str(calibration))
    if not mapping.is_file():
        missing.append(str(mapping))
    if not direct_yolo.is_file() and not legacy_yolo.is_file():
        missing.append(f"{direct_yolo} (or {legacy_yolo})")

    if missing:
        raise FileNotFoundError(
            "Missing Blueprint-AD prerequisite files:\n  "
            + "\n  ".join(missing)
        )


def resolve_adapter_path(workspace, reuse_adapter):
    workspace = Path(workspace)
    current = workspace / ADAPTER_FILENAME

    if not reuse_adapter:
        return current, False

    if current.is_file():
        return current, True

    # Compatibility with checkpoints generated by the previous local script.
    legacy = workspace / "sdf_pca64_aligner.pth"
    if legacy.is_file():
        print(
            "[WARNING] Reusing legacy adapter checkpoint name:",
            legacy,
        )
        return legacy, True

    return current, False


def build_click_arguments(args, class_name, workspace, adapter_path):
    root = dataset_root(args)

    click_args = [
        "--gpu",
        str(args.gpu),
        "--seed",
        str(args.seed),
        "--log_group",
        f"blueprint_{args.dataset}_{class_name}",
        "--log_project",
        LOG_PROJECT,
        "--workspace_dir",
        str(workspace),
        "--blueprint_checkpoint",
        str(adapter_path),
        "--yolo_conf_multiplier",
        str(YOLO_CONF_MULTIPLIER),
    ]

    if args.save_model:
        click_args.append("--save_patchcore_model")

    if args.save_anomaly_maps:
        click_args.append("--save_segmentation_images")

    click_args.append(str(Path(args.results_path)))

    # PatchCore configuration.
    click_args.append("patch_core")
    click_args.extend(["-b", BACKBONE])

    for layer in LAYERS:
        click_args.extend(["-le", layer])

    click_args.extend(
        [
            "--pretrain_embed_dimension",
            str(PRETRAIN_EMBED_DIM),
            "--target_embed_dimension",
            str(TARGET_EMBED_DIM),
            "--anomaly_scorer_num_nn",
            str(NUM_NEAREST_NEIGHBOURS),
            "--patchsize",
            str(PATCH_SIZE),
        ]
    )

    if args.faiss_on_gpu:
        click_args.append("--faiss_on_gpu")

    # 10% approximate-greedy coreset.
    click_args.extend(
        [
            "sampler",
            "-p",
            str(CORESET_PERCENTAGE),
            SAMPLER_NAME,
        ]
    )

    # Exactly one category per Blueprint PatchCore invocation.
    click_args.extend(
        [
            "dataset",
            "--resize",
            str(RESIZE),
            "--imagesize",
            str(IMAGE_SIZE),
            "--batch_size",
            str(BATCH_SIZE),
            "--num_workers",
            str(NUM_WORKERS),
            "-d",
            class_name,
            args.dataset,
            str(root),
        ]
    )

    return click_args


def run_category(args, class_name):
    root = dataset_root(args)
    workspace = category_workspace(args.runs_root, class_name)

    validate_blueprint_prerequisites(workspace)

    adapter_path, reused = resolve_adapter_path(
        workspace,
        args.reuse_adapter,
    )

    print()
    print("=" * 80)
    print(f"Blueprint PatchCore: {class_name}")
    print("=" * 80)
    print("Dataset:", args.dataset)
    print("Dataset path:", root)
    print("Workspace:", workspace)

    if reused:
        print("Coordinate adapter: reuse", adapter_path)
    else:
        print("Coordinate adapter: train before PatchCore")
        adapter_path = train_coordinate_adapter(
            dataset_path=str(root),
            dataset_name=args.dataset,
            class_name=class_name,
            workspace_dir=str(workspace),
            gpu=args.gpu,
            epochs=args.adapter_epochs,
            batch_size=args.adapter_batch_size,
        )

    print("Backbone:", BACKBONE)
    print("Layers:", list(LAYERS))
    print("Input size:", IMAGE_SIZE)
    print("Coreset percentage:", CORESET_PERCENTAGE)
    print("Nearest neighbours:", NUM_NEAREST_NEIGHBOURS)
    print("FAISS on GPU:", args.faiss_on_gpu)
    print("=" * 80)

    cli_arguments = build_click_arguments(
        args=args,
        class_name=class_name,
        workspace=workspace,
        adapter_path=adapter_path,
    )

    patchcore_main(
        args=cli_arguments,
        standalone_mode=False,
    )


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Train the per-category Blueprint-AD coordinate adapter and run "
            "Blueprint PatchCore."
        )
    )

    parser.add_argument(
        "--dataset",
        choices=["mvtec", "visa", "loco"],
        default="mvtec",
    )
    parser.add_argument(
        "--classes",
        nargs="+",
        default=["cable"],
        help='Category names, or "all" to discover every category.',
    )

    parser.add_argument(
        "--mvtec_ad_path",
        default=r"E:\data\MVtec",
    )
    parser.add_argument(
        "--visa_path",
        default=r"E:\data\VisA_new",
    )
    parser.add_argument(
        "--loco_path",
        default=r"E:\data\mvtec_loco_anomaly_detection",
    )

    parser.add_argument(
        "--runs_root",
        default="runs",
        help="Root containing runs/<category>/ Blueprint-AD prerequisites.",
    )
    parser.add_argument(
        "--results_path",
        default="output/patchcore_blueprint",
    )

    parser.add_argument("--gpu", type=int, default=0)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)

    parser.add_argument(
        "--adapter_epochs",
        type=int,
        default=40,
    )
    parser.add_argument(
        "--adapter_batch_size",
        type=int,
        default=4,
    )
    parser.add_argument(
        "--reuse_adapter",
        action="store_true",
        help=(
            "Reuse an existing coordinate_adapter.pth instead of retraining it. "
            "Without this flag the adapter is trained before every category."
        ),
    )

    parser.add_argument(
        "--faiss_on_gpu",
        action="store_true",
    )
    parser.add_argument(
        "--save_model",
        action="store_true",
    )
    parser.add_argument(
        "--save_anomaly_maps",
        action="store_true",
    )

    return parser.parse_args()


def main():
    args = parse_args()
    root = dataset_root(args)

    if not root.is_dir():
        raise FileNotFoundError(f"Dataset path does not exist: {root}")

    if len(args.classes) == 1 and args.classes[0].lower() == "all":
        classes = discover_classes(root)
    else:
        classes = args.classes

    for index, class_name in enumerate(classes, start=1):
        print()
        print(f"[{index}/{len(classes)}] {class_name}")
        run_category(args, class_name)


if __name__ == "__main__":
    main()
